var _ = require('underscore')
var fb = require('cloud/pattern-order.js')
var keys = require('cloud/keys.js')

var beforeSaveBook = require('cloud/before-save-book.js')
var afterSaveBook = require('cloud/after-save-book.js')
var beforeSaveTransaction = require('cloud/before-save-transaction.js')
var beforeSaveMyBook = require('cloud/before-save-mybook.js')
var searchFunction = require('cloud/search.js')
var searchFunction = require('cloud/update-counts.js')
